# Gemfile
source 'https://rubygems.org'

gem 'activerecord'
gem 'sinatra-activerecord'
gem 'pg'
gem 'sinatra', '~> 1.4', '>= 1.4.7'
gem 'rake'
gem 'rackup'
gem 'pry'
gem 'irb'
gem 'require_all'
gem 'pony'
gem 'bcrypt'
gem 'rotp'
gem 'rqrcode'
gem "sinatra-flash"
gem 'dotenv', require: 'dotenv/load'
gem 'faker'
gem 'database_cleaner'
gem 'sidekiq'
gem 'redis', '< 4.6'
